### ISSUE TITLE
Q: Does skyeye support Secure Coalitions in SRS, and/or multiple teams

### ISSUE THREAD

**Issue by ChaosRifle** [dharmab/skyeye#285]
as title states, asking for documentation on if skyeye support Secure Coalitions in SRS, and/or multiple teams like redfor and bluefor, both with and without secure coalition enabled.

**Comment by dharmab** [comment]
Hello!

> if skyeye support Secure Coalitions in SRS

This is currently not implemented, but it would not be difficult for me to add support.

> multiple teams like redfor and bluefor

My current strategy for this is to run two separate instances of SkyEye, one for each team. I had previously looked into supporting both using a since instance, but this adds a lot of complexity to save only around 2GB of RAM.

Note that I currently don't recommend using SkyEye for PvP because of https://github.com/dharmab/skyeye/issues/65 and because the bot currently has god-mode vision. I have some ideas for fixing both issues I'll be tackling in the coming weeks.
